### ISSUE TITLE
system "candelafvtt" uses pack.private which has been replaced with pack.ownership

### ISSUE THREAD

**Issue by illandhil** [ceriath/candelafvtt#10]
This system is targeting v11 foundry minimum but is using pack.private which is a v10 setting. I think in your system.json you need 
"ownership": {
        "PLAYER": "OBSERVER",
        "TRUSTED": "OBSERVER",
        "ASSISTANT": "OWNER",
        "GAMEMASTER": "OWNER"
	},
for private: false and you need
"ownership": {
	"PLAYER": "LIMITED",
	"TRUSTED": "OBSERVER",
        "ASSISTANT": "OWNER",
        "GAMEMASTER": "OWNER"
	},
for private: true from the couple things I read. Unless you want them set with some other setting. Below is the issue I referenced
https://github.com/foundryvtt/foundryvtt/issues/9318

I changed my local install and it makes the warning go away. Cheers.

**Comment by ceriath** [comment]
Hi!
Thank you for bringing it to my attention. That is probably a leftover setting from the Boilerplate, I'll fix it in the next release

**Comment by ceriath** [comment]
This has been fixed in v0.0.7 :)
