### ISSUE TITLE
Check boxes for equipment

### ISSUE THREAD

**Issue by Whirlmeister** [ceriath/candelafvtt#5]
Given the way equipment works in games, is there any way of implementing check boxes on the equipment to show which equipment has been selected?

If there isn’t we have a (slightly clunky) work around which works.

**Comment by ceriath** [comment]
Hi!
Yeah i can absolutely do that. My idea was to just add or remove equipment to/from the sheet, but i can see why that might be clunky in some cases, so I can absolutely add a checkbox for it.

**Comment by ceriath** [comment]
This has been released now in v0.0.5
